/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.samyuan1990.FabricJavaPool.Pool;

import java.io.File;
import java.lang.reflect.Proxy;

import com.github.samyuan1990.FabricJavaPool.config.FabricJavaPoolConfig;
import com.github.samyuan1990.FabricJavaPool.api.FabricConnection;
import com.github.samyuan1990.FabricJavaPool.cache.FabricConnectionImplCacheProxy;
import com.github.samyuan1990.FabricJavaPool.impl.FabricConnectionImpl;
import org.apache.commons.pool2.BasePooledObjectFactory;
import org.apache.commons.pool2.PooledObject;
import org.apache.commons.pool2.PooledObjectFactory;
import org.apache.commons.pool2.impl.DefaultPooledObject;
import org.apache.commons.pool2.impl.GenericObjectPool;
import org.hyperledger.fabric.sdk.Channel;
import org.hyperledger.fabric.sdk.HFClient;
import org.hyperledger.fabric.sdk.NetworkConfig;
import org.hyperledger.fabric.sdk.User;
import org.hyperledger.fabric.sdk.security.CryptoSuite;

public class FabricSDKPool extends GenericObjectPool<FabricConnection> {

    public FabricSDKPool(User appUser, String channel) {
        super(new SDKPoolFactory(appUser, channel), new FabricJavaPoolConfig());
    }

    public FabricSDKPool(User appUser, String channel, FabricJavaPoolConfig config) {
        super(new SDKPoolFactory(appUser, channel, config));
    }

    private static class SDKPoolFactory extends BasePooledObjectFactory<FabricConnection> implements PooledObjectFactory<FabricConnection> {

        private FabricJavaPoolConfig config =  new FabricJavaPoolConfig();
        private String networkConfigFile = "";
        private User appUser;
        private String channel = "";

        SDKPoolFactory(User appUser, String channel) {
            this.networkConfigFile = config.getNetworkConfigFile();
            this.appUser = appUser;
            this.channel = channel;
        }

        SDKPoolFactory(User appUser, String channel, FabricJavaPoolConfig config) {
            this.config = config;
            this.networkConfigFile = config.getNetworkConfigFile();
            this.appUser = appUser;
            this.channel = channel;
        }

        @Override
        public FabricConnection create() throws Exception {
            FabricConnectionImpl myConnection;
            CryptoSuite cryptoSuite = CryptoSuite.Factory.getCryptoSuite();
            HFClient hfclient = HFClient.createNewInstance();
            hfclient.setCryptoSuite(cryptoSuite);
            NetworkConfig networkConfig = NetworkConfig.fromYamlFile(new File(networkConfigFile));
            hfclient.setUserContext(appUser);
            hfclient.loadChannelFromConfig(channel, networkConfig);
            Channel myChannel = hfclient.getChannel(channel);
            myChannel.initialize();
            myConnection = new FabricConnectionImpl(hfclient, myChannel, appUser);
            if (config.isUseCache()) {
                FabricConnectionImplCacheProxy proxy = new FabricConnectionImplCacheProxy(myConnection, config.getCacheURL(), appUser.getName(), channel, config.getCacheTimeout());
                return (FabricConnection) Proxy.newProxyInstance(FabricConnectionImpl.class.getClassLoader(), new Class[]{FabricConnection.class}, proxy);
            } else {
                return myConnection;
            }

        }

        @Override
        public PooledObject<FabricConnection> wrap(FabricConnection obj) {
            return new DefaultPooledObject<>(obj);
        }

    }
}
